### ISSUE TITLE
Changing the --cnv-max-value parameter for plot-intraSVs does not work

### ISSUE THREAD

**Issue by kuba11** [XiaoTaoWang/EagleC#16]
Hello,

the --cnv-max-value parameter for plot-intraSVs does not seem work, as only the y axis labels seem to be changed, not the values on the plot. Pistures below:
![BRNO1727_chr7_chr7](https://user-images.githubusercontent.com/24893917/223140950-f4de0844-3f3e-4b60-881c-2d8bee3e5332.png)
![BRNO1727_chr7_chr7](https://user-images.githubusercontent.com/24893917/223140977-9366c86b-dc4b-4341-ac5f-46f19dfb044a.png)
or
![BRNO1727_chr8_chr8](https://user-images.githubusercontent.com/24893917/223141268-07d68fde-4729-444b-ba66-6e5f471928d2.png)
![BRNO1727_chr8_chr8](https://user-images.githubusercontent.com/24893917/223142742-617159ca-f0e7-40d8-9d9e-4f56ca1000a3.png)

Best wishes,
Kuba

**Comment by XiaoTaoWang** [comment]
Hi, thanks for this feedback. I have fixed it in the latest version 0.1.9. Can you upgrade your EagleC to this version (``pip install -U eaglec``) and try again?

**Comment by kuba11** [comment]
Hello,

yes, it works, thanks a lot!

Best wishes,
Kuba
