### ISSUE TITLE
Download manually for HPC

### ISSUE THREAD

**Issue by baozg** [XiaoTaoWang/EagleC#2]
Hi,

Typically, the HPC internet is disabled. How did I download the pretrained models manually in my laptop and then upload it to the offline HPC?

**Comment by XiaoTaoWang** [comment]
Sorry but I am a little bit confused ... if your HPC is disconnected, how could you even install EagleC and all the dependent packages? Just wanted to mention that the command "download-pretrained-models" need very few computational resource so can be run on your login node.

**Comment by baozg** [comment]
We can download eaglec in login node with pip. But for dropbox link, we cannot download it. How can I download the pretrained model and how to make a folder so that eaglc can find it?

**Comment by baozg** [comment]
We can download eaglec in login node with pip. But for dropbox link, we cannot download it. How can I download the pretrained model and how to make a folder so that eaglc can find it?

**Comment by XiaoTaoWang** [comment]
I see. We didn't realize that the mainland China has trouble in accessing dropbox. I will deposit models in another place and let you know once it's finished.

**Comment by baozg** [comment]
Thanks for your help. I download all model in my laptop and upload it to HPC.
