### ISSUE TITLE
EagleC HiChIP with Neoloopfinder

### ISSUE THREAD

**Issue by nyuhic** [XiaoTaoWang/EagleC#21]
Hello,

More a question than an issue. I have used EagleC to predict SVs in my HiChIP data and converted it to NeoLoopFinder format. I was wondering if I can use this as input to NeoLoopFinder or not? I know EagleC supports HiChIP data but not sure if NeoLoopFinder does?

Thanks

**Comment by nyuhic** [comment]
Thanks, I will try that. 

But just to make sure I understand correctly, when using ICE normalized mcools I would skip the calculate-cnv, segment-cnvs and correct-cnvs steps and directly use the assemble-cnv command on my data, right?

**Comment by XiaoTaoWang** [comment]
Yes, if you are going to use ICE-normalized values to identify neo-loops, you can skip them.

**Comment by nyuhic** [comment]
Thanks
