### ISSUE TITLE
Can you provide more information about the header of the output file ?

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [XiaoTaoWang/EagleC#42]
Hello, 
Can you provide more information about the header of the output file - especially the last 4 columns on the right ? 

<img width="355" alt="image" src="https://github.com/user-attachments/assets/fe186f4d-c8c5-4282-8cf4-83b1c6351a8f">

Thanks, K

**Comment by XiaoTaoWang** [comment]
Hi, the values in these columns represent the probability scores indicating the likelihood that a predicted SV belongs to a specific fusion type ("++", "+-", "-+", and "--").

**Comment by Krithika-Bhuvan** [comment]
Makes more sense now. Please add this line to your documentation.  Thank you !
